### PR TITLE
package maintenance

### PR DESCRIPTION
**Pull request by asherf**
* Add badges
* Fix various lint/python 3 deprecation issues
* use unittest (no longer need to import unittest2)
* Update supported python versions, python 3.3 & 3.4 are no longer supported

### CODE REVIEW

**Comment by asherf** [comment]
@rbm @rogerhu

**Comment by rbm** [comment]
lgtm

**Comment by rogerhu** [comment]
should we make you a collaborator?

**Comment by dhui** [comment]
I wouldn't mind being a collaborator either... 😉

**Pull request merged**
